function bill_template = getBillTemplate()

bill_template = struct(...
    'bill_id',{},...
    'bill_number',{},...
    'title',{},...
    'issue_category',{},...
    'sponsors',{},... % first vs co, also authors
    'date_introduced',{},...
    'date_last_action',{},...
    'house_data',{},...
    'passed_house',{},...
    'senate_data',{},...
    'passed_senate',{},...
    'passed_both',{},...
    'signed_into_law',{},...
    'complete',{});
% originated in house/senate?

end