function chamber_template = getChamberTemplate()
% GETCHAMBERTEMPLATE
% Template for a specific chamber

chamber_template = struct(...
    'committee_id',{},... % make sure multiple comittees are possible
    'committee_votes',{},...
    'chamber_votes',{},...
    'passed',{},...
    'final_yes',{},...
    'final_no',{},...
    'final_abstain',{},...
    'final_yes_percentage',{});

end