function vote_template = getVoteTemplate()

vote_template = struct('rollcall_id',{},...
    'description',{},...
    'date',{},...
    'yea',{},...
    'nay',{},...
    'nv',{},...
    'total_vote',{},...
    'yes_percent',{},...
    'yes_list',{},...
    'no_list',{},...
    'abstain_list',{});

end